# Generated by Django 4.0.1 on 2022-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_kcscgimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KcsPGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('supervisor', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='pdfs/kcs_Pohot_g_pdf/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
