# Generated by Django 4.0.1 on 2022-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_kcspgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcspgimage',
            name='photo',
            field=models.ImageField(upload_to='pdfs/kcs_Photo_g_pdf/'),
        ),
    ]
