# Generated by Django 4.0.1 on 2022-01-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_assistance_cee_good_works_lpc_sheets_opr_pcdo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siemens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('supervisor', models.CharField(max_length=225)),
                ('pdf', models.FileField(upload_to='pdfs/data_book/siemens')),
            ],
        ),
    ]
