# Generated by Django 4.0.1 on 2022-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_hbdown_hbup_mainlinedown_mainlineup_thbdown_thbup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rake_type', models.CharField(choices=[('S1', 'SIEMENS'), ('M1', 'MEMU'), ('BTM1', 'BTMEMU'), ('R1', 'ACRETRO')], default='S1', max_length=4)),
                ('coach_position', models.IntegerField(max_length=100)),
                ('be_dtc', models.IntegerField(max_length=224)),
                ('ke_dtc', models.IntegerField(max_length=224)),
                ('unit_no', models.IntegerField(max_length=224)),
                ('datetime', models.DateTimeField(max_length=224)),
                ('schedule_at', models.CharField(choices=[('KCS', 'KCS'), ('SCS', 'SCS'), ('NCS', 'NCS'), ('PA', 'PA')], max_length=4)),
                ('shift', models.CharField(choices=[('M', 'MORNING'), ('AF', 'AFTERNOON'), ('N', 'NIGHT')], max_length=4)),
                ('ia', models.CharField(max_length=224)),
                ('ic_quaterly', models.CharField(choices=[('1', 'IC-1'), ('2', 'IC-2'), ('3', 'IC-3'), ('4', 'IC-4')], max_length=4)),
                ('ust', models.CharField(max_length=224)),
                ('servicer_after', models.CharField(max_length=224)),
                ('washing', models.CharField(max_length=224)),
                ('mopping', models.CharField(max_length=224)),
                ('ti', models.CharField(max_length=224)),
                ('pdf', models.FileField(upload_to='pdfs/rake_master')),
            ],
        ),
    ]
