# Generated by Django 4.0.1 on 2022-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_schedulerake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerake',
            name='mopping',
            field=models.DateTimeField(max_length=224),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='unit_no',
            field=models.IntegerField(max_length=500),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='washing',
            field=models.DateTimeField(max_length=224),
        ),
    ]
