# Generated by Django 4.0.1 on 2022-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_schedulerake_mopping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerake',
            name='be_dtc',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='datetime',
            field=models.DateField(max_length=224),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='ia',
            field=models.CharField(choices=[('1', 'IA-1'), ('2', 'IA-2'), ('3', 'IA-3'), ('4', 'IA-4'), ('5', 'IA-5'), ('6', 'IA-6'), ('7', 'IA-7'), ('8', 'IA-8'), ('9', 'IA-9'), ('10', 'IA-10'), ('11', 'IA-11'), ('12', 'IA-12')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='ke_dtc',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='rake_type',
            field=models.CharField(choices=[('S1', 'SIEMENS'), ('M1', 'MEMU'), ('BTM1', 'BTMEMU'), ('R1', 'ACRETRO')], default='S1', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='ti',
            field=models.CharField(choices=[('1', 'TI-1'), ('2', 'TI-2'), ('3', 'TI-3'), ('4', 'TI-4'), ('5', 'TI-5'), ('6', 'TI-6'), ('7', 'TI-7'), ('8', 'TI-8'), ('9', 'TI-9'), ('10', 'TI-10'), ('11', 'TI-11'), ('12', 'TI-12')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedulerake',
            name='ust',
            field=models.CharField(choices=[('1', 'UST-1'), ('2', 'UST-2'), ('3', 'UST-3')], default='1', max_length=1),
        ),
    ]
