# Generated by Django 4.0.1 on 2022-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_schedulerake_be_dtc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rake_type', models.CharField(choices=[('S1', 'SIEMENS'), ('M1', 'MEMU'), ('BTM1', 'BTMEMU'), ('R1', 'ACRETRO')], default='S1', max_length=100)),
                ('coach_position', models.IntegerField(choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5'), ('SIX', '6'), ('SEVEN', '7'), ('EIGHT', '8'), ('NINE', '9'), ('TEN', '10'), ('ELEVEN', '11'), ('TWELVE', '12')], max_length=100)),
                ('unit_no', models.IntegerField(max_length=500)),
                ('rake_id', models.CharField(choices=[('S1', 'S1'), ('M1', 'M1'), ('BTM1', 'BTM1'), ('R1', 'R1')], max_length=100)),
                ('make', models.CharField(choices=[('1', 'RCF'), ('2', 'ICF'), ('3', 'BHEL')], max_length=100)),
                ('coach_no', models.IntegerField(max_length=100)),
                ('comm_date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
