# Generated by Django 4.0.1 on 2022-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_newrake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrake',
            name='coach_position',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newrake',
            name='unit_no',
            field=models.BigIntegerField(max_length=500),
        ),
    ]
