# Generated by Django 4.0.1 on 2022-02-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_ememo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ememo',
            old_name='railway',
            new_name='defects_reported',
        ),
        migrations.RemoveField(
            model_name='ememo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ememo',
            name='time',
        ),
        migrations.AlterField(
            model_name='ememo',
            name='IA',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='IC',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='M',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='TI',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='UST',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='W',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='image',
            field=models.ImageField(blank=True, upload_to='pdfs/ememo/'),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='investigation',
            field=models.TextField(blank=True, max_length=224),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='poh',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
