# Generated by Django 4.0.1 on 2022-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_ememo_ia_alter_ememo_ic_alter_ememo_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememo',
            name='report_signee',
            field=models.CharField(default=None, max_length=224, null=True),
        ),
    ]
