# Generated by Django 4.0.1 on 2022-02-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_ememo_report_signee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememo',
            name='investigation',
            field=models.TextField(blank=True, default=None, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='investigation_signee',
            field=models.CharField(default=None, max_length=224, null=True),
        ),
    ]
