# Generated by Django 4.0.1 on 2022-02-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_ememo_investigation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememo',
            name='IA',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='IC',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='M',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='TI',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='UST',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='W',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ememo',
            name='poh',
            field=models.DateField(default=None, null=True),
        ),
    ]
