# Generated by Django 4.0.2 on 2022-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_siemensdata_alter_ememo_investigation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siemensdata',
            old_name='POH_voer_Due',
            new_name='POH_over_Due',
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='Coach_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='Coach_Position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='Unit_No',
            field=models.SlugField(max_length=500),
        ),
    ]
