# Generated by Django 4.0.2 on 2022-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_poh_voer_due_siemensdata_poh_over_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siemensdata',
            name='Coach_No',
            field=models.CharField(max_length=100),
        ),
    ]
