# Generated by Django 4.0.2 on 2022-02-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_siemensdata_coach_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcretroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rake_ID', models.CharField(choices=[('S1', 'S1'), ('M1', 'M1'), ('BTM1', 'BTM1'), ('R1', 'R1')], default='R1', max_length=10)),
                ('Rake_Type', models.CharField(choices=[('S1', 'SIEMENS'), ('M1', 'MEMU'), ('BTM1', 'BTMEMU'), ('R1', 'ACRETRO')], default='R1', max_length=100)),
                ('Coach_Position', models.IntegerField()),
                ('Coach_No', models.CharField(max_length=100)),
                ('Unit_No', models.SlugField(max_length=500)),
                ('Make', models.CharField(choices=[('1', 'RCF'), ('2', 'ICF'), ('3', 'BHEL')], max_length=100)),
                ('Coach_Type', models.CharField(max_length=100)),
                ('Comm_Date', models.DateField(max_length=100)),
                ('Age_in_Yrs', models.FloatField(max_length=10)),
                ('Life_Left', models.FloatField(max_length=10)),
                ('Coach_Condemn_Date', models.DateField(max_length=100)),
                ('Latest_POH_Date', models.DateField(max_length=100)),
                ('EIS_after_POH_Date', models.DateField(max_length=100)),
                ('POH_over_Due', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemuBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rake_ID', models.CharField(choices=[('S1', 'S1'), ('M1', 'M1'), ('BTM1', 'BTM1'), ('R1', 'R1')], default='BTM1', max_length=10)),
                ('Rake_Type', models.CharField(choices=[('S1', 'SIEMENS'), ('M1', 'MEMU'), ('BTM1', 'BTMEMU'), ('R1', 'ACRETRO')], default='BTM1', max_length=100)),
                ('Coach_Position', models.IntegerField()),
                ('Coach_No', models.CharField(max_length=100)),
                ('Unit_No', models.SlugField(max_length=500)),
                ('Make', models.CharField(choices=[('1', 'RCF'), ('2', 'ICF'), ('3', 'BHEL')], max_length=100)),
                ('Coach_Type', models.CharField(max_length=100)),
                ('Comm_Date', models.DateField(max_length=100)),
                ('Age_in_Yrs', models.FloatField(max_length=10)),
                ('Life_Left', models.FloatField(max_length=10)),
                ('Coach_Condemn_Date', models.DateField(max_length=100)),
                ('Latest_POH_Date', models.DateField(max_length=100)),
                ('EIS_after_POH_Date', models.DateField(max_length=100)),
                ('POH_over_Due', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemuRCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rake_ID', models.CharField(choices=[('S1', 'S1'), ('M1', 'M1'), ('BTM1', 'BTM1'), ('R1', 'R1')], default='M1', max_length=10)),
                ('Rake_Type', models.CharField(choices=[('S1', 'SIEMENS'), ('M1', 'MEMU'), ('BTM1', 'BTMEMU'), ('R1', 'ACRETRO')], default='M1', max_length=100)),
                ('Coach_Position', models.IntegerField()),
                ('Coach_No', models.CharField(max_length=100)),
                ('Unit_No', models.SlugField(max_length=500)),
                ('Make', models.CharField(choices=[('1', 'RCF'), ('2', 'ICF'), ('3', 'BHEL')], max_length=100)),
                ('Coach_Type', models.CharField(max_length=100)),
                ('Comm_Date', models.DateField(max_length=100)),
                ('Age_in_Yrs', models.FloatField(max_length=10)),
                ('Life_Left', models.FloatField(max_length=10)),
                ('Coach_Condemn_Date', models.DateField(max_length=100)),
                ('Latest_POH_Date', models.DateField(max_length=100)),
                ('EIS_after_POH_Date', models.DateField(max_length=100)),
                ('POH_over_Due', models.DateField(max_length=100)),
            ],
        ),
    ]
